version: '1.0'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    restart: always
    volumes:
      - pg_diploma_data:/var/lib/postgresql/data/
    ports:
    - "5432:5432"
    healthcheck:
      test: pg_isready -U ${DB_USER} -d ${DB_NAME}
      timeout: 3s
      retries: 10
      interval: 3s

  api:
    build: .
    env_file: .env
    environment:
      DB_HOST: db
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    volumes:
      - ./users:/opt/users
      - ./sellers:/opt/sellers
      - ./products:/opt/products
      - ./online_sale:/opt/online_sale
      - django_static:/opt/static

volumes:
  pg_diploma_data:
  django_static:
